/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhimSlugRouteImport } from './routes/phim.$slug'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiSuggestRouteImport } from './routes/api/suggest'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiScheduleRouteImport } from './routes/api/schedule'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiFavoritesRouteImport } from './routes/api/favorites'
import { Route as ApiBrowseRouteImport } from './routes/api/browse'
import { Route as XemSlugTapChar123episodeChar125RouteImport } from './routes/xem.$slug.tap-{$episode}'
import { Route as ApiWatchlistToggleRouteImport } from './routes/api/watchlist.toggle'
import { Route as ApiWatchlistNoteRouteImport } from './routes/api/watchlist.note'
import { Route as ApiNotificationsUnreadCountRouteImport } from './routes/api/notifications.unread-count'
import { Route as ApiNotificationsMarkReadRouteImport } from './routes/api/notifications.mark-read'
import { Route as ApiMoviesHomeRouteImport } from './routes/api/movies/home'
import { Route as ApiMoviesSlugRouteImport } from './routes/api/movies.$slug'
import { Route as ApiFavoritesToggleRouteImport } from './routes/api/favorites.toggle'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiActorsSearchRouteImport } from './routes/api/actors.search'
import { Route as ApiActorsNameRouteImport } from './routes/api/actors.$name'
import { Route as ApiMoviesSlugRelatedRouteImport } from './routes/api/movies.$slug.related'
import { Route as ApiHistorySlugEpRouteImport } from './routes/api/history.$slug.$ep'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhimSlugRoute = PhimSlugRouteImport.update({
  id: '/phim/$slug',
  path: '/phim/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestRoute = ApiSuggestRouteImport.update({
  id: '/api/suggest',
  path: '/api/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScheduleRoute = ApiScheduleRouteImport.update({
  id: '/api/schedule',
  path: '/api/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFavoritesRoute = ApiFavoritesRouteImport.update({
  id: '/api/favorites',
  path: '/api/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowseRoute = ApiBrowseRouteImport.update({
  id: '/api/browse',
  path: '/api/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const XemSlugTapChar123episodeChar125Route =
  XemSlugTapChar123episodeChar125RouteImport.update({
    id: '/xem/$slug/tap-{$episode}',
    path: '/xem/$slug/tap-{$episode}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWatchlistToggleRoute = ApiWatchlistToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ApiWatchlistRoute,
} as any)
const ApiWatchlistNoteRoute = ApiWatchlistNoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => ApiWatchlistRoute,
} as any)
const ApiNotificationsUnreadCountRoute =
  ApiNotificationsUnreadCountRouteImport.update({
    id: '/unread-count',
    path: '/unread-count',
    getParentRoute: () => ApiNotificationsRoute,
  } as any)
const ApiNotificationsMarkReadRoute =
  ApiNotificationsMarkReadRouteImport.update({
    id: '/mark-read',
    path: '/mark-read',
    getParentRoute: () => ApiNotificationsRoute,
  } as any)
const ApiMoviesHomeRoute = ApiMoviesHomeRouteImport.update({
  id: '/api/movies/home',
  path: '/api/movies/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoviesSlugRoute = ApiMoviesSlugRouteImport.update({
  id: '/api/movies/$slug',
  path: '/api/movies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFavoritesToggleRoute = ApiFavoritesToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ApiFavoritesRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActorsSearchRoute = ApiActorsSearchRouteImport.update({
  id: '/api/actors/search',
  path: '/api/actors/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActorsNameRoute = ApiActorsNameRouteImport.update({
  id: '/api/actors/$name',
  path: '/api/actors/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoviesSlugRelatedRoute = ApiMoviesSlugRelatedRouteImport.update({
  id: '/related',
  path: '/related',
  getParentRoute: () => ApiMoviesSlugRoute,
} as any)
const ApiHistorySlugEpRoute = ApiHistorySlugEpRouteImport.update({
  id: '/$slug/$ep',
  path: '/$slug/$ep',
  getParentRoute: () => ApiHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/favorites': typeof ApiFavoritesRouteWithChildren
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/schedule': typeof ApiScheduleRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/phim/$slug': typeof PhimSlugRoute
  '/api/actors/$name': typeof ApiActorsNameRoute
  '/api/actors/search': typeof ApiActorsSearchRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/favorites/toggle': typeof ApiFavoritesToggleRoute
  '/api/movies/$slug': typeof ApiMoviesSlugRouteWithChildren
  '/api/movies/home': typeof ApiMoviesHomeRoute
  '/api/notifications/mark-read': typeof ApiNotificationsMarkReadRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/watchlist/note': typeof ApiWatchlistNoteRoute
  '/api/watchlist/toggle': typeof ApiWatchlistToggleRoute
  '/xem/$slug/tap-{$episode}': typeof XemSlugTapChar123episodeChar125Route
  '/api/history/$slug/$ep': typeof ApiHistorySlugEpRoute
  '/api/movies/$slug/related': typeof ApiMoviesSlugRelatedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/favorites': typeof ApiFavoritesRouteWithChildren
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/schedule': typeof ApiScheduleRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/phim/$slug': typeof PhimSlugRoute
  '/api/actors/$name': typeof ApiActorsNameRoute
  '/api/actors/search': typeof ApiActorsSearchRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/favorites/toggle': typeof ApiFavoritesToggleRoute
  '/api/movies/$slug': typeof ApiMoviesSlugRouteWithChildren
  '/api/movies/home': typeof ApiMoviesHomeRoute
  '/api/notifications/mark-read': typeof ApiNotificationsMarkReadRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/watchlist/note': typeof ApiWatchlistNoteRoute
  '/api/watchlist/toggle': typeof ApiWatchlistToggleRoute
  '/xem/$slug/tap-{$episode}': typeof XemSlugTapChar123episodeChar125Route
  '/api/history/$slug/$ep': typeof ApiHistorySlugEpRoute
  '/api/movies/$slug/related': typeof ApiMoviesSlugRelatedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/favorites': typeof ApiFavoritesRouteWithChildren
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/schedule': typeof ApiScheduleRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/phim/$slug': typeof PhimSlugRoute
  '/api/actors/$name': typeof ApiActorsNameRoute
  '/api/actors/search': typeof ApiActorsSearchRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/favorites/toggle': typeof ApiFavoritesToggleRoute
  '/api/movies/$slug': typeof ApiMoviesSlugRouteWithChildren
  '/api/movies/home': typeof ApiMoviesHomeRoute
  '/api/notifications/mark-read': typeof ApiNotificationsMarkReadRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/watchlist/note': typeof ApiWatchlistNoteRoute
  '/api/watchlist/toggle': typeof ApiWatchlistToggleRoute
  '/xem/$slug/tap-{$episode}': typeof XemSlugTapChar123episodeChar125Route
  '/api/history/$slug/$ep': typeof ApiHistorySlugEpRoute
  '/api/movies/$slug/related': typeof ApiMoviesSlugRelatedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/api/browse'
    | '/api/favorites'
    | '/api/history'
    | '/api/notifications'
    | '/api/schedule'
    | '/api/search'
    | '/api/suggest'
    | '/api/translate'
    | '/api/watchlist'
    | '/phim/$slug'
    | '/api/actors/$name'
    | '/api/actors/search'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/favorites/toggle'
    | '/api/movies/$slug'
    | '/api/movies/home'
    | '/api/notifications/mark-read'
    | '/api/notifications/unread-count'
    | '/api/watchlist/note'
    | '/api/watchlist/toggle'
    | '/xem/$slug/tap-{$episode}'
    | '/api/history/$slug/$ep'
    | '/api/movies/$slug/related'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/api/browse'
    | '/api/favorites'
    | '/api/history'
    | '/api/notifications'
    | '/api/schedule'
    | '/api/search'
    | '/api/suggest'
    | '/api/translate'
    | '/api/watchlist'
    | '/phim/$slug'
    | '/api/actors/$name'
    | '/api/actors/search'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/favorites/toggle'
    | '/api/movies/$slug'
    | '/api/movies/home'
    | '/api/notifications/mark-read'
    | '/api/notifications/unread-count'
    | '/api/watchlist/note'
    | '/api/watchlist/toggle'
    | '/xem/$slug/tap-{$episode}'
    | '/api/history/$slug/$ep'
    | '/api/movies/$slug/related'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/api/browse'
    | '/api/favorites'
    | '/api/history'
    | '/api/notifications'
    | '/api/schedule'
    | '/api/search'
    | '/api/suggest'
    | '/api/translate'
    | '/api/watchlist'
    | '/phim/$slug'
    | '/api/actors/$name'
    | '/api/actors/search'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/favorites/toggle'
    | '/api/movies/$slug'
    | '/api/movies/home'
    | '/api/notifications/mark-read'
    | '/api/notifications/unread-count'
    | '/api/watchlist/note'
    | '/api/watchlist/toggle'
    | '/xem/$slug/tap-{$episode}'
    | '/api/history/$slug/$ep'
    | '/api/movies/$slug/related'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiBrowseRoute: typeof ApiBrowseRoute
  ApiFavoritesRoute: typeof ApiFavoritesRouteWithChildren
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ApiNotificationsRoute: typeof ApiNotificationsRouteWithChildren
  ApiScheduleRoute: typeof ApiScheduleRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSuggestRoute: typeof ApiSuggestRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiWatchlistRoute: typeof ApiWatchlistRouteWithChildren
  PhimSlugRoute: typeof PhimSlugRoute
  ApiActorsNameRoute: typeof ApiActorsNameRoute
  ApiActorsSearchRoute: typeof ApiActorsSearchRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiMoviesSlugRoute: typeof ApiMoviesSlugRouteWithChildren
  ApiMoviesHomeRoute: typeof ApiMoviesHomeRoute
  XemSlugTapChar123episodeChar125Route: typeof XemSlugTapChar123episodeChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phim/$slug': {
      id: '/phim/$slug'
      path: '/phim/$slug'
      fullPath: '/phim/$slug'
      preLoaderRoute: typeof PhimSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest': {
      id: '/api/suggest'
      path: '/api/suggest'
      fullPath: '/api/suggest'
      preLoaderRoute: typeof ApiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedule': {
      id: '/api/schedule'
      path: '/api/schedule'
      fullPath: '/api/schedule'
      preLoaderRoute: typeof ApiScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favorites': {
      id: '/api/favorites'
      path: '/api/favorites'
      fullPath: '/api/favorites'
      preLoaderRoute: typeof ApiFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browse': {
      id: '/api/browse'
      path: '/api/browse'
      fullPath: '/api/browse'
      preLoaderRoute: typeof ApiBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xem/$slug/tap-{$episode}': {
      id: '/xem/$slug/tap-{$episode}'
      path: '/xem/$slug/tap-{$episode}'
      fullPath: '/xem/$slug/tap-{$episode}'
      preLoaderRoute: typeof XemSlugTapChar123episodeChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist/toggle': {
      id: '/api/watchlist/toggle'
      path: '/toggle'
      fullPath: '/api/watchlist/toggle'
      preLoaderRoute: typeof ApiWatchlistToggleRouteImport
      parentRoute: typeof ApiWatchlistRoute
    }
    '/api/watchlist/note': {
      id: '/api/watchlist/note'
      path: '/note'
      fullPath: '/api/watchlist/note'
      preLoaderRoute: typeof ApiWatchlistNoteRouteImport
      parentRoute: typeof ApiWatchlistRoute
    }
    '/api/notifications/unread-count': {
      id: '/api/notifications/unread-count'
      path: '/unread-count'
      fullPath: '/api/notifications/unread-count'
      preLoaderRoute: typeof ApiNotificationsUnreadCountRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/notifications/mark-read': {
      id: '/api/notifications/mark-read'
      path: '/mark-read'
      fullPath: '/api/notifications/mark-read'
      preLoaderRoute: typeof ApiNotificationsMarkReadRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/movies/home': {
      id: '/api/movies/home'
      path: '/api/movies/home'
      fullPath: '/api/movies/home'
      preLoaderRoute: typeof ApiMoviesHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movies/$slug': {
      id: '/api/movies/$slug'
      path: '/api/movies/$slug'
      fullPath: '/api/movies/$slug'
      preLoaderRoute: typeof ApiMoviesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favorites/toggle': {
      id: '/api/favorites/toggle'
      path: '/toggle'
      fullPath: '/api/favorites/toggle'
      preLoaderRoute: typeof ApiFavoritesToggleRouteImport
      parentRoute: typeof ApiFavoritesRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actors/search': {
      id: '/api/actors/search'
      path: '/api/actors/search'
      fullPath: '/api/actors/search'
      preLoaderRoute: typeof ApiActorsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actors/$name': {
      id: '/api/actors/$name'
      path: '/api/actors/$name'
      fullPath: '/api/actors/$name'
      preLoaderRoute: typeof ApiActorsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movies/$slug/related': {
      id: '/api/movies/$slug/related'
      path: '/related'
      fullPath: '/api/movies/$slug/related'
      preLoaderRoute: typeof ApiMoviesSlugRelatedRouteImport
      parentRoute: typeof ApiMoviesSlugRoute
    }
    '/api/history/$slug/$ep': {
      id: '/api/history/$slug/$ep'
      path: '/$slug/$ep'
      fullPath: '/api/history/$slug/$ep'
      preLoaderRoute: typeof ApiHistorySlugEpRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
  }
}

interface ApiFavoritesRouteChildren {
  ApiFavoritesToggleRoute: typeof ApiFavoritesToggleRoute
}

const ApiFavoritesRouteChildren: ApiFavoritesRouteChildren = {
  ApiFavoritesToggleRoute: ApiFavoritesToggleRoute,
}

const ApiFavoritesRouteWithChildren = ApiFavoritesRoute._addFileChildren(
  ApiFavoritesRouteChildren,
)

interface ApiHistoryRouteChildren {
  ApiHistorySlugEpRoute: typeof ApiHistorySlugEpRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistorySlugEpRoute: ApiHistorySlugEpRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

interface ApiNotificationsRouteChildren {
  ApiNotificationsMarkReadRoute: typeof ApiNotificationsMarkReadRoute
  ApiNotificationsUnreadCountRoute: typeof ApiNotificationsUnreadCountRoute
}

const ApiNotificationsRouteChildren: ApiNotificationsRouteChildren = {
  ApiNotificationsMarkReadRoute: ApiNotificationsMarkReadRoute,
  ApiNotificationsUnreadCountRoute: ApiNotificationsUnreadCountRoute,
}

const ApiNotificationsRouteWithChildren =
  ApiNotificationsRoute._addFileChildren(ApiNotificationsRouteChildren)

interface ApiWatchlistRouteChildren {
  ApiWatchlistNoteRoute: typeof ApiWatchlistNoteRoute
  ApiWatchlistToggleRoute: typeof ApiWatchlistToggleRoute
}

const ApiWatchlistRouteChildren: ApiWatchlistRouteChildren = {
  ApiWatchlistNoteRoute: ApiWatchlistNoteRoute,
  ApiWatchlistToggleRoute: ApiWatchlistToggleRoute,
}

const ApiWatchlistRouteWithChildren = ApiWatchlistRoute._addFileChildren(
  ApiWatchlistRouteChildren,
)

interface ApiMoviesSlugRouteChildren {
  ApiMoviesSlugRelatedRoute: typeof ApiMoviesSlugRelatedRoute
}

const ApiMoviesSlugRouteChildren: ApiMoviesSlugRouteChildren = {
  ApiMoviesSlugRelatedRoute: ApiMoviesSlugRelatedRoute,
}

const ApiMoviesSlugRouteWithChildren = ApiMoviesSlugRoute._addFileChildren(
  ApiMoviesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  ApiBrowseRoute: ApiBrowseRoute,
  ApiFavoritesRoute: ApiFavoritesRouteWithChildren,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ApiNotificationsRoute: ApiNotificationsRouteWithChildren,
  ApiScheduleRoute: ApiScheduleRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSuggestRoute: ApiSuggestRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiWatchlistRoute: ApiWatchlistRouteWithChildren,
  PhimSlugRoute: PhimSlugRoute,
  ApiActorsNameRoute: ApiActorsNameRoute,
  ApiActorsSearchRoute: ApiActorsSearchRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiMoviesSlugRoute: ApiMoviesSlugRouteWithChildren,
  ApiMoviesHomeRoute: ApiMoviesHomeRoute,
  XemSlugTapChar123episodeChar125Route: XemSlugTapChar123episodeChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
