/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiMoviesHomeRouteImport } from './routes/api/movies/home'
import { Route as ApiHistorySlugEpRouteImport } from './routes/api/history.$slug.$ep'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoviesHomeRoute = ApiMoviesHomeRouteImport.update({
  id: '/api/movies/home',
  path: '/api/movies/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistorySlugEpRoute = ApiHistorySlugEpRouteImport.update({
  id: '/$slug/$ep',
  path: '/$slug/$ep',
  getParentRoute: () => ApiHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/movies/home': typeof ApiMoviesHomeRoute
  '/api/history/$slug/$ep': typeof ApiHistorySlugEpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/movies/home': typeof ApiMoviesHomeRoute
  '/api/history/$slug/$ep': typeof ApiHistorySlugEpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/movies/home': typeof ApiMoviesHomeRoute
  '/api/history/$slug/$ep': typeof ApiHistorySlugEpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/favorites'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/api/history'
    | '/api/movies/home'
    | '/api/history/$slug/$ep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/favorites'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/api/history'
    | '/api/movies/home'
    | '/api/history/$slug/$ep'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/favorites'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/api/history'
    | '/api/movies/home'
    | '/api/history/$slug/$ep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  FavoritesRoute: typeof FavoritesRoute
  HistoryRoute: typeof HistoryRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ApiMoviesHomeRoute: typeof ApiMoviesHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movies/home': {
      id: '/api/movies/home'
      path: '/api/movies/home'
      fullPath: '/api/movies/home'
      preLoaderRoute: typeof ApiMoviesHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/$slug/$ep': {
      id: '/api/history/$slug/$ep'
      path: '/$slug/$ep'
      fullPath: '/api/history/$slug/$ep'
      preLoaderRoute: typeof ApiHistorySlugEpRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
  }
}

interface ApiHistoryRouteChildren {
  ApiHistorySlugEpRoute: typeof ApiHistorySlugEpRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistorySlugEpRoute: ApiHistorySlugEpRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  FavoritesRoute: FavoritesRoute,
  HistoryRoute: HistoryRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ApiMoviesHomeRoute: ApiMoviesHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
